name = "Dummyvar"
uuid = "5d02951d-65b4-45d8-b6c0-f168f9df2c9e"
authors = ["fabrizio-leone"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
